### PR TITLE
Workshop data image classification

### PR DESCRIPTION
**Pull request by drinkingkazu**
Workshop data image classification notebook added along with io/util tools

### CODE REVIEW

**Comment by pdeperio** [comment]
This won't affect the existing pre-workshop notebooks, right? Do you need someone to test before merging?

**Comment by drinkingkazu** [comment]
Dear Patrick,

There is a minor change in the MNIST notebook where I lied (may be noticed by someone who knows torch well, unlikely by participants). This does not need to be enhanced.

The reason I sent the pull request is in case you prefer for me to point out the notebooks in hatchmal repo rather than my forked version during today's meeting. If this isn't something to be concern about, please ignore that pull request!

**Review by pdeperio — APPROVED** [review]
ok, i will just grant you merge privileges since you're working too fast for me to review ;)

**Comment by drinkingkazu** [comment]
Ah, right, sorry I forgot to comment on the "test" part. I have to change the data path for this to work on AWS. Sorry, probably the requirement for merge is that it works on AWS, and this should have been rejected... I'll put data on aws so it would work.

**Pull request merged**
